### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by ZHEQIUSHUI** [davidfrp/Depictions.ImageBox.NET#1]
thank you  for your code

and i want to get the pixel location with mouse point in OnMouseMove event,how can i do this,thanks a lot!!!

**Comment by davidfrp** [comment]
It can be done quite easily, though I've yet to document this project very well. Well, if anything at all.

To find the pixel that the mouse is positioned above, simply do:
```csharp
imageBox_MouseMove = (object s, MouseEventArgs e) =>
{
    Point locationWithinImage = imageBox.PointToFullImage(mouseEventargs.Location);
};

imageBox.MouseMove += imageBox_MouseMove;
```

_You'll have to check whether the point you've got is outside the bounds of the image._

I hope this helps, and I'll gladly answer any other questions you might have.

**Comment by ZHEQIUSHUI** [comment]
wow,this is a excellent job !
thanks a lot !
i will keep follow this Repository !

**Comment by davidfrp** [comment]
I'm glad to hear that. Thanks. It's certainly a nice incentive for me to document and update the ugly bits of code that is still left.
